name: HACS

on:
  push:
    branches: [main]
  pull_request:

jobs:
  hacs:
    runs-on: ubuntu-latest
    name: HACS Action
    steps:
      - uses: actions/checkout@v4

      - name: HACS Validation
        uses: hacs/action@main
        with:
          category: integration
